- name: gather facts
  setup:

- block:
  - name: Setup Users
    user:
      name: piranha
      shell: /bin/bash
      state: present
      groups: "{{ admin_group }}"

  - name: Adding github ssh keys
    authorized_key: user={{ item }} key=https://github.com/precurse.keys
    with_items:
      - piranha
      - root

  - name: Enable account
    command: passwd -N piranha
    when: ansible_distribution == "SmartOS"

  - name: Enable EPEL Repo for CentOS
    yum:
      name: epel-release
      state: present
    when: ansible_distribution == "CentOS"

  - name: Enable SCL Repo for CentOS
    yum:
      name: centos-release-scl
      state: present
    when: ansible_distribution == "CentOS"

  - name: Disable Debian auto-start daemons on install
    shell: echo "exit 101" > /usr/sbin/policy-rc.d creates=/usr/sbin/policy-rc.d
    when: ansible_os_family == "Debian"

  - import_tasks: auto_updates.yml

  - name: Install common packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - sudo
      - tmux
      - git
    ignore_errors: yes

  - name: Clone dotfiles
    git:
      repo: "https://github.com/precurse/dotfiles"
      dest: "/home/piranha/dotfiles"
      clone: yes
    become_user: piranha

  - name: Link dotfiles
    file:
      state: link
      force: yes
      src: "/home/piranha/dotfiles/{{ item }}"
      dest: "/home/piranha/.{{ item }}"
    with_items:
      - profile
      - bashrc
      - bash_profile
    become_user: piranha

  - name: Setting hostname on SmartOS
    command: sm-set-hostname {{ alias }}
    when: alias is defined and ansible_distribution == "SmartOS"
    changed_when: no

  - name: Setting hostname on Linux
    hostname: name={{ alias }}
    when: alias is defined and ansible_system == "Linux"
    changed_when: no
  become: yes

